# Generated by Django 2.2.3 on 2019-07-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=30)),
                ('Department', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=30)),
            ],
        ),
    ]
